<?php
/**
 * defaults.php
 * Default configuration.
 *
 ***************************************************************************************
 * DO NOT EDIT THIS FILE OR ANY FILE IN THE SUBDIRECTORIES!!!!  YOUR APP WILL BREAK!!! *
 ***************************************************************************************
 * 
 * @author zburnham
 * @version 0.0.1
 * 
 */
return array(
    'Application' => include('Application/ApplicationConfig.php'),
    'Autoloader'  => include('Autoloader/AutoloaderConfig.php'),
    
);